export const demoLayoutCopy = {
  es: {
    launch: 'Reacomodar muebles', title: 'Tu distribución de la casa', back: 'Volver a la casa',
    intro: 'Elegí qué objetos incluir y arrastralos en la escena. Los cambios quedan en este navegador.',
    original: 'Distribución original · guardado local automático', saved: 'Distribución guardada en este navegador',
    unavailable: 'No se pudo guardar en este navegador. Los cambios duran hasta que cierres o recargues la página.',
    recovered: 'Algunos cambios guardados ya no eran compatibles. Se recuperó la distribución disponible.',
    reset: 'Restaurar distribución original', undo: 'Deshacer', redo: 'Rehacer', three: '3D', top: 'Plano',
    objects: 'Objetos de la casa', choose: 'Elegí un objeto', movable: 'Movible', fixed: 'Fijo',
    generated: 'Objetos generados', draft: 'Borrador', select: 'Seleccionar', addAndSelect: 'Agregar y seleccionar', inScene: 'En la escena',
    fixedHelp: 'Podés quitar o incluir esta instalación. Su posición es fija.',
    moveHelp: 'Arrastrá el objeto o usá las flechas del teclado. R lo gira; Escape cancela un arrastre.',
    x: 'Posición X (m)', z: 'Posición Z (m)', rotation: 'Giro (°)', rotate: 'Girar 90°',
    rotationControls: 'Girar el objeto seleccionado', rotateLeft: 'Girar 90° a la izquierda', rotateRight: 'Girar 90° a la derecha',
    error: 'El objeto debe quedar dentro de la planta. Probá otra posición.',
    accountTitle: 'Tu propio proyecto', accountHelp: 'Iniciá sesión para crear proyectos, guardar versiones y agregar nuevos objetos.',
    signIn: 'Ir a mis proyectos', history: 'Ver historial de objetos', room: 'Ambiente',
    hint: 'Muebles movibles · instalaciones fijas · cambios solo en este navegador',
    selectHelp: 'Seleccioná un objeto en la escena o en la lista para ver si se puede mover.',
    controls: 'Arrastrá un mueble para moverlo; arrastrá el fondo para cambiar la vista. Rueda para acercar.',
  },
  en: {
    launch: 'Rearrange furniture', title: 'Your layout of the house', back: 'Back to the house',
    intro: 'Choose which objects to include and drag them in the scene. Changes stay in this browser.',
    original: 'Original layout · automatic local saving', saved: 'Layout saved in this browser',
    unavailable: 'This browser could not save the layout. Changes last until you close or reload the page.',
    recovered: 'Some saved changes were no longer compatible. The available layout has been recovered.',
    reset: 'Restore original layout', undo: 'Undo', redo: 'Redo', three: '3D', top: 'Plan',
    objects: 'Objects in the house', choose: 'Choose an object', movable: 'Movable', fixed: 'Fixed',
    generated: 'Generated objects', draft: 'Draft', select: 'Select', addAndSelect: 'Add and select', inScene: 'In the scene',
    fixedHelp: 'You can remove or include this installation. Its position is fixed.',
    moveHelp: 'Drag the object or use the arrow keys. R rotates it; Escape cancels a drag.',
    x: 'X position (m)', z: 'Z position (m)', rotation: 'Rotation (°)', rotate: 'Rotate 90°',
    rotationControls: 'Rotate the selected object', rotateLeft: 'Rotate 90° left', rotateRight: 'Rotate 90° right',
    error: 'The object must stay inside the floor. Try another position.',
    accountTitle: 'Your own project', accountHelp: 'Sign in to create projects, save versions and add new objects.',
    signIn: 'Go to my projects', history: 'Browse object history', room: 'Room',
    hint: 'Movable furniture · fixed installations · changes stay in this browser',
    selectHelp: 'Select an object in the scene or the list to see whether it can move.',
    controls: 'Drag furniture to move it; drag the background to change your view. Scroll to zoom.',
  },
} as const
